spring.application.name=engine_solution

server.port = 8080

# Database Configuration (Assuming PostgreSQL + PostGIS)
spring.datasource.url=jdbc:postgresql://localhost:5432/agri_credit_solution
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# OpenFeign Configuration (URL for your Python ML microservice)
ml.service.url=http://localhost:8000

# JWT SECURITY (For Flutter App Login)
# ==========================================
# This is a 256-bit Hex key used to sign the tokens. Keep this secret in production!
agricredit.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiration time: 86400000 milliseconds = 1 Day
agricredit.app.jwtExpirationMs=86400000

# Swagger Documentation Path
springdoc.swagger-ui.path=/swagger-ui.html

# LOGGING
logging.level.root=INFO
logging.level.com.agricredit=DEBUG

# Show SQL queries in the console to help you debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevents Jackson from crashing on empty geometric beans
spring.jackson.serialization.fail-on-empty-beans=false