spring.application.name=engine_solution
server.port=${PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/agri_credit_solution}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ml.service.url=${ML_SERVICE_URL:http://localhost:8000}

agricredit.app.jwtSecret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
agricredit.app.jwtExpirationMs=86400000

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=INFO
logging.level.com.agricredit=DEBUG

# Your ACTIVE AgroMonitoring API Key for live Satellite NDVI data
agromonitoring.api.key=b6cabec8360584b54f5b57725c91d195