spring.application.name=engine_solution
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

ml.service.url=${ML_SERVICE_URL}

agricredit.app.jwtSecret=${JWT_SECRET}
agricredit.app.jwtExpirationMs=86400000

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=INFO
logging.level.com.agricredit=INFO
